baseURL: "https://docs.ci.openshift.org/"
languageCode: "en-us"
title: "Openshift CI docs"
theme: "docsy"
sectionPagesMenu: "main"
params:
  offlineSearch: true
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "dracula"
menu:
  main:
  - name: Step Registry
    url: https://steps.ci.openshift.org/
