baseURL: "https://docs.ci.openshift.org/"
languageCode: "en-us"
title: "Openshift CI docs"
theme: "docsy"
sectionPagesMenu: "main"
contentDir: "content/en"
params:
  offlineSearch: true
    #pygmentsCodefences: true
    #pygmentsCodefencesGuessSyntax: true
    #pygmentsStyle: "dracula"
  github_repo: "https://github.com/openshift/ci-docs"
menu:
  main:
  - name: Step Registry
    url: https://steps.ci.openshift.org/
  - name: GitHub
    url: https://github.com/openshift/ci-tools
markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: "dracula"
    tabWidth: 4
